### ISSUE TITLE
Targeting html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [WennDann/f1-3-c2p1-colmar-academy#6]
Nothing wrong with using html to set styles for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/WennDann/f1-3-c2p1-colmar-academy/blob/master/ColmarAcademy/resources/css/style.css#L16-L20

**Comment by WennDann** [comment]
@griffinlacek Ah, that's amazing! I was wondering sometimes during this project, why some of the styles I set just there in html did not apply where I expected it. And now going back in the older projects, I found that I usually used the body tag for doing this. I can't explain myself, why I did it with html this time. Really weird. And thanks a lot for the link to that discussion. I have to think a bit about the different use cases for each, since it really seems to be good to use both, depending on your case. Thanks
